Admin_Dashboard!/Models/ErrorViewModel.cs
namespace Admin_Dashboard_.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Admin_Dashboard!/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Admin_Dashboard_.Controllers
{
    public class AuthenticationController : Controller
    {
        public IActionResult SignIn()
        {
            return View();
        }

        public IActionResult SignUp()
        {
            return View();
        }
        public IActionResult Passwordreset()
        {
            return View();
        }
    }
}

Admin_Dashboard!/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Admin_Dashboard_.Controllers
{
    public class ClientsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
       
    }
}

Admin_Dashboard!/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Admin_Dashboard_.Controllers
{
    public class CountriesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Admin_Dashboard!/Controllers/EnumeratorsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Admin_Dashboard_.Controllers
{
    public class EnumeratorsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Admin_Dashboard!/Controllers/HomeController.cs
using Admin_Dashboard_.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Admin_Dashboard_.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Admin_Dashboard!/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;

namespace Admin_Dashboard_.Controllers
{
    public class UsersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Admin_Dashboard!/Views/Authentication/Passwordreset.cshtml
@{
    Layout = "_LayoutAuthentication";
    ViewData["Title"] = "Reset password";
    var ReturnUrl = ViewBag.ReturnUrl;
}



<body id="body" class="auth-page" style="background-image: url('assets/images/p-1.png'); background-size: cover; background-position: center center;">
    <!-- Log In page -->
    <div class="container">
        <div class="row vh-100 d-flex justify-content-center">
            <div class="col-12 align-self-center">
                <div class="row">
                    <div class="col-lg-5 mx-auto">
                        <div class="card">
                            <div class="card-body p-0 auth-header-box">
                                <div class="text-center p-3">
                                    <a href="index.html" class="logo logo-admin">
                                        <img src="./images/logos/logo.jpeg" height="50" alt="logo" class="auth-logo">
                                    </a>
                                    <h4 class="mt-3 mb-1 fw-semibold text-white font-18">Reset Password For Metrica</h4>   
                                    <p class="text-muted  mb-0">Enter your Email and instructions will be sent to you!</p>  
                                </div>
                            </div>
                            <div class="card-body pt-0">
                                <form class="my-4" action="index.html">
                                    <div class="form-group mb-3">
                                        <label class="form-label" for="username">Email</label>
                                        <input type="text" class="form-control" id="userEmail" name="Email" placeholder="Enter Email Address">                               
                                    </div><!--end form-group--> 

                                    <div class="form-group mb-0 row">
                                        <div class="col-12">
                                            <button class="btn btn-primary w-100" type="button">Reset <i class="fas fa-sign-in-alt ms-1"></i></button>
                                        </div><!--end col--> 
                                    </div> <!--end form-group-->                           
                                </form><!--end form-->
                                <div class="text-center text-muted">
                                    <p class="mb-1">Remember It ?  <a href="auth-register.html" class="text-primary ms-2">Sign in here</a></p>
                                </div>
                            </div><!--end card-body-->
                            <div class="card-body bg-light-alt text-center">
                                &copy; <script>
                                    document.write(new Date().getFullYear())
                                </script> Inco Management Console                                           
                            </div>
                        </div><!--end card-->
                    </div><!--end col-->
                </div><!--end row-->
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->

    <!-- App js -->
    <script src="assets/js/app.js"></script>
    
</body>

Admin_Dashboard!/Views/Authentication/SignIn.cshtml
@{
    Layout = "_LayoutAuthentication";
    ViewData["Title"] = "Sign In";
    var ReturnUrl = ViewBag.ReturnUrl;
}

<div class="container-md">
    <div class="row vh-100 d-flex justify-content-center">
        <div class="col-12 align-self-center">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-4 mx-auto">
                        <div class="card">
                            <div class="card-body p-0 auth-header-box">
                                <div class="text-center p-4">
                                    <a href="index.html" class="logo logo-admin">
                                        <img src="~/images/logos/Cornell-logo.png" alt="Cornell"
                                             class="auth-logo">
                                    </a>
                                    <h4 class="mt-4 mb-1 fw-semibold font-18">Cornell Management Portal</h4>
                                    <p class="text-muted  mb-0">Login into your account</p>
                                </div>
                            </div>
                            <div class="card-body pt-0">
                                <form class="auth-form my-4" id="signIn" name="signIn" method="post" autocomplete="off">
                                    @Html.AntiForgeryToken()
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        <div class="input-group mb-3">
                                            <span class="auth-form-icon">
                                                <i class="dripicons-user"></i>
                                            </span>
                                            <input type="text" class="form-control" placeholder="Enter email">
                                        </div>
                                    </div><!--end form-group-->

                                    <div class="form-group">
                                        <label for="userpassword">Password</label>
                                        <div class="input-group mb-3">
                                            <span class="auth-form-icon">
                                                <i class="dripicons-lock"></i>
                                            </span>
                                            <input type="password" class="form-control" placeholder="Enter password">
                                        </div>
                                    </div><!--end form-group-->

                                    <div class="form-group row mt-4">
                                        <div class="col-sm-12 text-center">
                                            <a asp-action="Passwordreset" asp-controller="Authentication" class="text-muted font-13"><i class="dripicons-lock"></i> Forgot password?</a>
                                        </div><!--end col-->
                                    </div><!--end form-group-->
                                   @* <input id="returnUrl" type="hidden" asp-for="ReturnUrl" value="" />*@
                                    <div class="form-group mb-0 row">
                                            <div class="col-12">
                                                <div class="d-grid mt-3">
                                                    <button class="btn btn-outline-primary btn-round d-flex mx-auto justify-content-center" style="min-width:200px;" type="submit" id="signin-submit-button">SignIn </button>
                                                </div>
                                            </div>
                                            <!--end col-->
                                        </div>
                                </form><!--end form-->
                                <div class="m-3 text-center text-muted">
                                    <p class="mb-0">
                                        Don't have an account ? <a asp-action="Signup" asp-controller="Authentication" class="text-primary ms-2">Free Register</a>
                                    </p>
                                </div>
                            </div>
                            <!--end card-body-->
                        </div>
                        <!--end card-->
                    </div>
                    <!--end col-->
                </div>
                <!--end row-->
            </div>
            <!--end card-body-->
        </div>
        <!--end col-->
    </div>
    <!--end row-->
</div>

Admin_Dashboard!/Views/Authentication/SignUp.cshtml
@{
    Layout = "_LayoutAuthentication";
    ViewData["Title"] = "Sign up";
    var ReturnUrl = ViewBag.ReturnUrl;
}

<div class="container-md">
    <div class="row vh-100 d-flex justify-content-center">
        <div class="col-12 align-self-center">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-4 mx-auto">
                        <div class="card">
                            <div class="card-body p-0 auth-header-box">
                                <div class="text-center p-4">
                                    <a href="index.html" class="logo logo-admin">
                                        <img src="~/images/logos/Cornell-logo.png" alt="Inco"
                                             class="auth-logo">
                                    </a>
                                    <h4 class="mt-4 mb-1 fw-semibold font-18">Cornell Management Portal</h4>
                                    <p class="text-muted  mb-0">Create An Account</p>
                                </div>
                            </div>
                            <div class="card-body pt-0">
                                <form class="auth-form my-4" id="signUp" name="signUp" method="post" autocomplete="off">
                                    @Html.AntiForgeryToken()

                                    <div row>

                                        <div col>
                                            <div class="form-group">
                                            <label for="FirstName">First Name</label>
                                            <div class="input-group mb-3">
                                                <span class="auth-form-icon">
                                                    <i class="dripicons-user"></i>
                                                </span>
                                                <input type="text" class="form-control" placeholder="Enter First Name">
                                            </div>
                                        </div><!--end form-group-->
                                        <div class="form-group">
                                            <label for="LastName">Last Name</label>
                                            <div class="input-group mb-3">
                                                <span class="auth-form-icon">
                                                    <i class="dripicons-user"></i>
                                                </span>
                                                <input type="text" class="form-control" placeholder="Enter Last Name">
                                            </div>
                                        </div><!--end form-group-->
                                        </div>
                                        
                                    </div>
                                    

                                    

                                       <div class="form-group">
                                        <label for="PhoneNumber">Phone Number</label>
                                        <div class="input-group mb-3">
                                            <span class="auth-form-icon">
                                                <i class="dripicons-user"></i>
                                            </span>
                                            <input type="text" class="form-control" placeholder="Enter Phone Number">
                                        </div>
                                    </div><!--end form-group-->

                                       <div class="form-group">
                                        <label for="EmailAddress">Email Address</label>
                                        <div class="input-group mb-3">
                                            <span class="auth-form-icon">
                                                <i class="dripicons-user"></i>
                                            </span>
                                                <input type="text" class="form-control" placeholder="Enter Email Address">
                                        </div>
                                    </div><!--end form-group-->

                                    <div class="form-group">
                                        <label for="userpassword">Password</label>
                                        <div class="input-group mb-3">
                                            <span class="auth-form-icon">
                                                <i class="dripicons-lock"></i>
                                            </span>
                                            <input type="password" class="form-control" placeholder="Enter password">
                                        </div>
                                    </div><!--end form-group-->

                                 
                                    <div class="form-group mb-0 row">
                                            <div class="col-12">
                                                <div class="d-grid mt-3">
                                                    <button class="btn btn-outline-primary btn-round d-flex mx-auto justify-content-center" style="min-width:200px;" type="submit" id="signup-submit-button">Register</button>
                                                </div>
                                            </div>
                                            <!--end col-->
                                        </div>
                                </form><!--end form-->
                                <div class="m-3 text-center text-muted">
                                    <p class="mb-0">
                                        Already have an account ? <a asp-action="SignIn" asp-controller="Authentication" class="text-primary ms-2">SignIn</a>
                                    </p>
                                </div>
                            </div>
                            <!--end card-body-->
                        </div>
                        <!--end card-->
                    </div>
                    <!--end col-->
                </div>
                <!--end row-->
            </div>
            <!--end card-body-->
        </div>
        <!--end col-->
    </div>
    <!--end row-->
</div>

Admin_Dashboard!/Views/Countries/Index.cshtml
@{
    ViewData["Title"] = "Countries";
}
@section Styles {

    <link href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" type="text/css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/css/jqueryui-editable.css" rel="stylesheet"/>
    <link href="~/plugins/select/selectr.min.css" rel="stylesheet"/>
}
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="float-end">
                <button type="button" class="btn btn-outline-primary mt-3 btn-round ms-auto d-flex" data-bs-toggle="modal" data-bs-target="#exampleModal">+Add New</button>
                
            </div>           
              <h2 class="page-title mt-3">Registered Countries</h2>              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div>
<div class="row">
    <div class="col-12">
        <div class="card mt-3">
            <div class="card-body">
                <div class="card-body">
                        <div class="mb-3">
                            <div class="row form-row">
                                <div class="col-md col-sm-4">
                                    <label for="">Class</label>
                                    <input type="text" name="From" class="form-control" placeholder="Class">
                                </div>
                                <div class="col-md col-sm-4">
                                    <label for="inputEmail4">stream </label>
                                    <input type="text" name="To" class="form-control" placeholder="Stream">
                                </div>
                                <div class="col-md col-sm-4">
                                    <label for="inputEmail4">Status:</label>
                                    <select id="T_Status" name="Status" class="custom-select form-control" placeholder="Status">
                                        <option selected>All</option>
                                        <option value="Pending">Pending Approval</option>
                                        <option>Processing</option>
                                        <option value="Processed">Successfull</option>
                                        <option>Failed</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <table id="countriesTable" class="table dt-responsive">
                            <thead>
                                <th></th>
                                <th>Flag</th>
                                <th>Country Code</th>
                                <th>Country Name</th>
                                <th>Status</th>
                                <th>Action</th>
                                
                            </thead>
                        </table>
                </div>               
            </div>
        </div>
    </div>
</div>

<!-- modal-dialog -->

<div class="modal fade bd-example-modal-lg" id ="exampleModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class = "modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header"> 
                <h6 class="modal-title m-0 text-dark" id="AddAccountModal">Add Country Details</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="add-account-form" name="addaccountform" action="" method="post" novalidate>
                    @Html.AntiForgeryToken()
                            <div class="form-group row">
                                <div class="col-md-6 mb-2">
                                    <label for="name">Country Id</label>
                                    <input type="text" placeholder="Country Id" name="Name" required class="form-control"/>
                                </div>
                                <div class="col-md-6 mb-2">
                                    <label for="name">Country Name</label>
                                    <input type="text" placeholder="Country Name" name="Name" required class="form-control"/>
                                </div>
                                <div class="col-md-6 mb-2">
                                    <label for="name">Country Code</label>
                                    <input type="text" name="CountryCode" placeholder="Country Code" required class="form-control"/>
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <div class="col-md-12 mb-2">
                                    <label for="name">Description</label>
                                    <textarea type="text" name="LongDescription" required placeholder="Long description" class="form-control"></textarea>
                                </div>
                          
                            </div>
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <button type="submit" class="btn btn-outline-primary btn-round px-3 py-2 mt-4" id="add-client-submit-button">Create Country</button>                     
                            </div> 
                </form>                
            </div>
        </div>                                
    </div>  
</div>

@section Scripts
{
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/js/jqueryui-editable.min.js"></script>
    <script type="text/javascript" src="~/plugins/select/selectr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/libphonenumber-js/1.10.6/libphonenumber-js.min.js" integrity="sha512-DIE7nTrAVZlfQH99EttilfOthEIDoL77dPajcUN4diozul9IgSDHUdgW0Kfqj5Qi6k1LQ53ESujDZSo00FEpYQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/pages/country.js"></script>
}

Admin_Dashboard!/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/images/favicon.ico">

    <!-- App css -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.css" rel="stylesheet" type="text/css" />
    <link href="~/css/custom.css" rel="stylesheet" type="text/css" />
    @RenderSection("Styles", false)

</head>
<body id="body">
    <partial name="_LayoutMenu" />
    <!-- Top Bar Start -->
    <partial name="_LayoutHeader" />
    <!-- Top Bar End -->

    <div class="page-wrapper">

        <!-- Page Content-->
        <div class="page-content-tab">

            <div class="container-fluid">
                @RenderBody()
            </div>

            <!--Start Rightbar-->
            <!--Start Rightbar/offcanvas-->
            <div class="offcanvas offcanvas-end" tabindex="-1" id="Appearance" aria-labelledby="AppearanceLabel">
                <div class="offcanvas-header border-bottom">
                    <h5 class="m-0 font-14" id="AppearanceLabel">Appearance</h5>
                    <button type="button" class="btn-close text-reset p-0 m-0 align-self-center"
                        data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <h6>Account Settings</h6>
                    <div class="p-2 text-start mt-3">
                        <div class="form-check form-switch mb-2">
                            <input class="form-check-input" type="checkbox" id="settings-switch1">
                            <label class="form-check-label" for="settings-switch1">Auto updates</label>
                        </div>
                        <!--end form-switch-->
                        <div class="form-check form-switch mb-2">
                            <input class="form-check-input" type="checkbox" id="settings-switch2" checked>
                            <label class="form-check-label" for="settings-switch2">Location Permission</label>
                        </div>
                        <!--end form-switch-->
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="settings-switch3">
                            <label class="form-check-label" for="settings-switch3">Show offline Contacts</label>
                        </div>
                        <!--end form-switch-->
                    </div>
                    <!--end /div-->
                    <h6>General Settings</h6>
                    <div class="p-2 text-start mt-3">
                        <div class="form-check form-switch mb-2">
                            <input class="form-check-input" type="checkbox" id="settings-switch4">
                            <label class="form-check-label" for="settings-switch4">Show me Online</label>
                        </div>
                        <!--end form-switch-->
                        <div class="form-check form-switch mb-2">
                            <input class="form-check-input" type="checkbox" id="settings-switch5" checked>
                            <label class="form-check-label" for="settings-switch5">Status visible to all</label>
                        </div>
                        <!--end form-switch-->
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="settings-switch6">
                            <label class="form-check-label" for="settings-switch6">Notifications Popup</label>
                        </div>
                        <!--end form-switch-->
                    </div>
                    <!--end /div-->
                </div>
                <!--end offcanvas-body-->
            </div>
            <!--end Rightbar/offcanvas-->
            <!--end Rightbar-->
            <partial name="_LayoutFooter" />
        </div>
        <!-- end page content -->
    </div>
    <!-- end page-wrapper -->

    <!-- App js -->
    <script src="~/js/app.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

Admin_Dashboard!/Views/Shared/_LayoutAuthentication.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Management console - auth</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href="~/images/favicon.ico">

    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.css" rel="stylesheet" type="text/css" />
    <link href="~/css/custom.css" rel="stylesheet" type="text/css" />

</head>

<body id="body" class="auth-page"
    style="background-image: url('/images/p-1.png'); background-size: cover; background-position: center center;">

    @RenderBody()

    <!-- Sweet-Alert  -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- Auth js -->
    <script src="~/pages/authentication.js"></script>
    <!-- App js -->
    <script src="~/js/app.js"></script>

</body>
</html>

Admin_Dashboard!/Views/Shared/_LayoutFooter.cshtml
<footer class="footer text-center text-sm-start">
    &copy; @DateTime.Now.Year Cornell Recruitment Limited
</footer>